name: Cpp check GHA

on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:  borbelytomii/tests-image:latest
    steps:
      - uses: actions/checkout@v2
      - name: run Makefile
        run:  make all_tests 
      - name: Uploading cppcheck as artifact
        uses: actions/upload-artifact@v2
        with:
          name: cppcheck_for_artifact
          path: ./cppcheck_for_artifact.txt
      - run: g++-9 -std=c++17 -lstdc++fs *.cpp -Wall -Wextra -g
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: make all_tests